from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, Optional

import folium
import streamlit as st
from folium import CircleMarker, Map, PolyLine
from streamlit_folium import st_folium


def render_sidebar() -> None:
    with st.sidebar:
        st.header("How to use")
        st.markdown(
            """
            1. **Upload users file** (required)  
            2. (Optional) upload **roads file** if you want poles to follow roads  
            3. Adjust **heuristic** parameters  
            4. Choose whether to **allow isolated buildings to remain unserved**  
            5. Click **Run LV design**  
            6. Inspect the map and download GeoJSON outputs
            """
        )
        st.markdown("---")
        st.markdown("**Example data**: see the `examples/` folder in this project.")


def render_intro_section(methodology_img: Path) -> None:
    st.title("LV Distribution Network - Topology Assessment")
    st.markdown(
        """
        This app provides a **first-order topology assessment** for Low-Voltage (LV) distribution networks, starting from
        building connection points and, optionally, a road layout. The goal is not detailed engineering design, but to
        quickly explore how **settlement geometry and simple planning rules** translate into pole count, network length,
        and cost.

        The workflow has two main steps. First, **pole locations are generated and buildings are associated to poles**
        using a heuristic approach. When roads are available, candidate poles are sampled along road segments; otherwise,
        poles are placed inside the settlement based on clustering of nearby buildings. Once poles are defined, they are connected into a **single radial LV network** by computing a
        **Minimum Spanning Tree (MST)**, which minimizes total cable length while avoiding loops. A final **engineering post-processing** step is then applied through the **Max LV span between poles**
        parameter. If any LV segment is longer than this threshold, it is subdivided by inserting intermediate
        support poles, preserving one connected network while avoiding unrealistically long spans.
    """
    )

    if methodology_img.exists():
        st.image(
            str(methodology_img),
            width="stretch",
            caption="Process flow for LV distribution network design",
        )

    st.markdown("---")


def render_upload_section() -> tuple[Optional[Any], str, Optional[Any]]:
    st.subheader("Upload connection data")

    users_file = st.file_uploader(
        "Users file (GeoPackage `.gpkg` or Excel `.xlsx`) **required**",
        type=["gpkg", "xlsx"],
        key="dist_users_file",
    )
    if users_file:
        st.success("Users file uploaded.")

    follow_roads_mode = st.radio(
        "Pole placement strategy",
        options=("Follow roads (requires roads file)", "Free placement"),
        index=0,
        key="dist_follow_roads_mode",
    )

    roads_file: Optional[Any] = None
    if follow_roads_mode.startswith("Follow roads"):
        roads_file = st.file_uploader(
            "Roads file (GeoPackage `.gpkg`)",
            type=["gpkg"],
            key="dist_roads_file",
        )
        if roads_file:
            st.success("Roads file uploaded.")
        else:
            st.info("If you don't have a roads file, switch to **Free placement**.")

    st.markdown("---")
    return users_file, follow_roads_mode, roads_file


def render_params_section(
    *,
    default_sampling_distance_m: int,
    default_user_distance_m: int,
    default_max_associations: int,
) -> Dict[str, Any]:
    st.subheader("Heuristic pole placement and customer association")

    col1, col2, col3 = st.columns(3)

    with col1:
        road_pole_spacing_m = st.slider(
            "Road pole spacing (candidate sampling) [m]",
            min_value=10,
            max_value=200,
            value=int(default_sampling_distance_m),
            step=5,
            key="dist_spacing",
            help=(
                "Used ONLY when 'Follow roads' is selected. Candidate pole locations are "
                "generated by sampling points along road segments at this spacing. "
                "Smaller values means more candidate poles (denser), potentially shorter user-pole distances."
            ),
        )

    with col2:
        max_user_connection_radius_m = st.slider(
            "Max user-pole connection radius [m]",
            min_value=10,
            max_value=200,
            value=int(default_user_distance_m),
            step=5,
            key="dist_radius",
            help=(
                "Maximum distance allowed for connecting a building to an existing pole during association. "
                "Smaller values means fewer buildings associated per pole, which may require additional poles (or become standalone candidates)."
            ),
        )

    with col3:
        max_users_per_pole = st.slider(
            "Max users per pole [#]",
            min_value=1,
            max_value=100,
            value=int(default_max_associations),
            step=1,
            key="dist_max_users",
            help=(
                "Upper limit on how many buildings can be assigned to the same pole. "
                "Smaller values â†’ more poles to serve the same number of users."
            ),
        )

    st.subheader("Network span control (post-processing)")

    max_pole_span_m = st.slider(
        "Max LV span between poles (engineering cap) [m]",
        min_value=road_pole_spacing_m,
        max_value=150,
        value=40,
        step=5,
        key="dist_span",
        help=(
            "Applied AFTER the MST is computed. If an MST edge is longer than this value, "
            "the tool inserts intermediate support poles to subdivide the span. "
            "This keeps a single connected tree while limiting long unsupported LV segments."
        ),
    )

    st.markdown("---")
    st.subheader("Coverage behaviour")

    allow_unserved_isolated = st.checkbox(
        "Allow very isolated buildings to remain unserved (standalone candidates)",
        value=False,
        key="dist_allow_unserved",
        help=(
            "If enabled, very small or isolated clusters of buildings will not be "
            "connected by LV. They will be shown as red points and can be treated "
            "as standalone system candidates."
        ),
    )

    standalone_criterion = "economic"
    standalone_economics: Dict[str, float] = {}
    min_cluster_size = 1

    if allow_unserved_isolated:
        criterion_label = st.radio(
            "Standalone criterion",
            options=(
                "Economic (differential cost)",
                "Topological (legacy, min cluster size)",
            ),
            index=0,
            key="dist_standalone_criterion",
            help=(
                "Economic: a cluster is connected only if its marginal connection "
                "cost (last mile + service drops + new pole + backbone extension, "
                "shared across the cluster) does not exceed the differential "
                "budget (c_standalone - c_generation) x E per building. "
                "Topological: historical criterion based on cluster size only."
            ),
        )

        if criterion_label.startswith("Economic"):
            standalone_criterion = "economic"
            min_cluster_size = 2  # kept only for legacy consumers of params

            c1, c2 = st.columns(2)
            with c1:
                sa_cost = st.slider(
                    "Standalone system cost c_sa [$/kWh]",
                    min_value=0.10, max_value=3.00, value=0.90, step=0.05,
                    key="dist_sa_cost",
                    help="Levelised cost of the standalone alternative (e.g. SHS).",
                )
                energy_y = st.slider(
                    "Energy per building [kWh/year]",
                    min_value=50, max_value=1000, value=180, step=10,
                    key="dist_sa_energy",
                )
            with c2:
                gen_cost = st.slider(
                    "Additional generation cost c_gen [$/kWh]",
                    min_value=0.05, max_value=1.50, value=0.38, step=0.01,
                    key="dist_gen_cost",
                    help="Levelised cost of serving one extra kWh from the mini-grid plant.",
                )
                horizon = st.slider(
                    "Evaluation horizon [years]",
                    min_value=5, max_value=30, value=20, step=1,
                    key="dist_sa_horizon",
                )

            threshold = max(float(sa_cost) - float(gen_cost), 0.0) * float(energy_y) * float(horizon)
            st.caption(
                f"Connection budget per building: **{threshold:,.0f} $** "
                f"= (c_sa - c_gen) x E x N. A cluster is connected only if its "
                f"marginal connection cost per building stays below this budget."
            )
            standalone_economics = {
                "standalone_cost_usd_per_kwh": float(sa_cost),
                "gen_cost_usd_per_kwh": float(gen_cost),
                "energy_kwh_per_year": float(energy_y),
                "horizon_years": float(horizon),
            }
        else:
            standalone_criterion = "topological"
            min_cluster_size = st.slider(
                "Minimum cluster size for LV connection",
                min_value=1,
                max_value=10,
                value=2,
                step=1,
                key="dist_min_cluster_size",
                help=(
                    "Clusters of unserved buildings smaller than this size will not get "
                    "a new pole and will remain as standalone candidates."
                ),
            )
            st.info(
                "Selective coverage mode (legacy): only clusters with at least the "
                "chosen size are connected by LV. Smaller, isolated clusters are "
                "flagged as standalone candidates (red points)."
            )
    else:
        st.info(
            "Full coverage mode: the heuristic will try to connect all buildings "
            "by LV. In very sparse areas this may lead to long LV extensions even "
            "if they exceed your intuitive distance thresholds."
        )

    st.markdown("---")

    return {
        "road_pole_spacing_m": road_pole_spacing_m,
        "max_user_connection_radius_m": max_user_connection_radius_m,
        "max_users_per_pole": max_users_per_pole,
        "max_pole_span_m": max_pole_span_m,
        "allow_unserved_isolated": allow_unserved_isolated,
        "min_cluster_size": min_cluster_size,
        "standalone_criterion": standalone_criterion,
        "standalone_economics": standalone_economics,
    }


def render_action_buttons() -> tuple[bool, bool]:
    left, right, _ = st.columns([1, 1, 1])
    with left:
        run_clicked = st.button("Run LV design", type="primary", width="stretch")
    with right:
        clear_clicked = st.button("Clear results", width="stretch")
    return run_clicked, clear_clicked


def _metric_row(metrics: Dict[str, float]) -> None:
    st.text(
        "Estimated total line length of the LV system, split between the main backbone "
        "(pole-to-pole feeder network) and the final connections from poles to individual buildings."
    )

    c1, c2, c3 = st.columns(3)
    c1.metric("Total network length [km]", f"{metrics.get('total_network_length_km', 0.0):.2f}")
    c2.metric("LV backbone length [km]", f"{metrics.get('backbone_length_km', 0.0):.2f}")
    c3.metric("Service drop length [km]", f"{metrics.get('service_drop_length_km', 0.0):.2f}")

    st.text(
        "Number of poles required for the LV network. Serving poles supply buildings directly, "
        "while support poles are added only to limit span lengths and do not host connections."
    )

    c1, c2, c3 = st.columns(3)
    c1.metric("Total poles", int(metrics.get("num_poles_total", 0)))
    c2.metric("Serving poles", int(metrics.get("num_poles_serving", 0)))
    c3.metric("Support poles", int(metrics.get("num_poles_support", 0)))

    st.text(
        "Coverage of the settlement by the LV network. Standalone candidates are buildings "
        "left unconnected due to isolation or clustering constraints."
    )

    c1, c2, c3 = st.columns(3)
    c1.metric("Total buildings", int(metrics.get("num_buildings", 0)))
    c2.metric("Grid-served buildings", int(metrics.get("num_served", 0)))
    c3.metric("Standalone candidates", int(metrics.get("num_unserved", 0)))


def _geom_to_latlon(geometry):
    if geometry is None or geometry.is_empty:
        return None
    point = geometry if geometry.geom_type == "Point" else geometry.representative_point()
    return (point.y, point.x)


def _make_map_lv(
    center: tuple[float, float],
    gdf_served,
    gdf_unserved,
    gdf_poles,
    mst_edges_latlon,
    gdf_roads=None,
) -> Map:
    m = folium.Map(location=[center[0], center[1]], zoom_start=15)

    if gdf_roads is not None and not gdf_roads.empty:
        for _, row in gdf_roads.iterrows():
            geom = row.geometry
            if geom is None:
                continue
            if geom.geom_type == "LineString":
                coords = [(lat, lon) for lon, lat in geom.coords]
                PolyLine(locations=coords, color="gray", weight=3, opacity=0.7).add_to(m)
            elif geom.geom_type == "MultiLineString":
                for line in geom.geoms:
                    coords = [(lat, lon) for lon, lat in line.coords]
                    PolyLine(locations=coords, color="gray", weight=3, opacity=0.7).add_to(m)

    for (lat1, lon1), (lat2, lon2) in mst_edges_latlon:
        PolyLine(
            locations=[(lat1, lon1), (lat2, lon2)],
            color="blue",
            weight=2,
            opacity=0.9,
        ).add_to(m)

    if gdf_poles is not None and not gdf_poles.empty:
        for _, row in gdf_poles.iterrows():
            latlon = _geom_to_latlon(row.geometry)
            if latlon is None:
                continue
            y, x = latlon
            pole_type = str(row.get("pole_type", "base")).strip().lower()

            if pole_type == "support":
                CircleMarker(
                    location=[y, x],
                    radius=4,
                    color="#555555",
                    weight=3,
                    fill=True,
                    fill_color="#BBBBBB",
                    fill_opacity=0.9,
                    tooltip="Support pole",
                ).add_to(m)
            elif pole_type == "serving":
                CircleMarker(
                    location=[y, x],
                    radius=4,
                    color="black",
                    weight=2,
                    fill=True,
                    fill_color="black",
                    fill_opacity=1.0,
                    tooltip="Serving pole",
                ).add_to(m)
            else:
                CircleMarker(
                    location=[y, x],
                    radius=2,
                    color="black",
                    weight=1,
                    fill=True,
                    fill_color="black",
                    fill_opacity=0.7,
                    tooltip="Non-serving pole",
                ).add_to(m)

    if gdf_served is not None and not gdf_served.empty:
        for _, row in gdf_served.iterrows():
            latlon = _geom_to_latlon(row.geometry)
            if latlon is None:
                continue
            y, x = latlon
            CircleMarker(
                location=[y, x],
                radius=2,
                color="green",
                fill=True,
                fill_color="green",
                fill_opacity=0.8,
            ).add_to(m)

    if gdf_unserved is not None and not gdf_unserved.empty:
        for _, row in gdf_unserved.iterrows():
            latlon = _geom_to_latlon(row.geometry)
            if latlon is None:
                continue
            y, x = latlon
            CircleMarker(
                location=[y, x],
                radius=3,
                color="red",
                fill=True,
                fill_color="red",
                fill_opacity=0.9,
            ).add_to(m)

    return m


def _render_downloads(downloads: Dict[str, Any]) -> None:
    if not downloads:
        return

    nodes = downloads.get("nodes_geojson")
    edges = downloads.get("edges_geojson")
    assoc = downloads.get("associations_csv")
    meta_template = downloads.get("building_metadata_template_csv")

    if not nodes and not edges and not assoc and not meta_template:
        return

    st.subheader("Download outputs")

    st.text(
        "Export LV topology as GeoJSON files (for GIS) and the building-to-pole association CSV.\n"
        "- Nodes include pole_id and pole_type (serving / non_serving / support)\n"
        "- Edges represent the pole-to-pole MST network\n"
        "- associations.csv maps each served building_id to its serving pole_id (support poles excluded by design).\n"
        "- building_metadata.csv is a pre-filled template for the validation step: edit category and weight, then upload in Grid Validation."
    )

    if nodes:
        st.download_button(
            "Download poles (nodes) GeoJSON",
            data=nodes,
            file_name="lv_poles.geojson",
            mime="application/geo+json",
        )

    if edges:
        st.download_button(
            "Download LV network (GeoJSON)",
            data=edges,
            file_name="lv_network.geojson",
            mime="application/geo+json",
        )

    if assoc:
        st.download_button(
            "Download building pole associations (CSV)",
            data=assoc,
            file_name="associations.csv",
            mime="text/csv",
        )

    if meta_template:
        st.download_button(
            "Download building metadata template (CSV)",
            data=meta_template,
            file_name="building_metadata.csv",
            mime="text/csv",
            help=(
                "Pre-filled with all building IDs. "
                "Edit 'category' (HHs / Buz / PH) and 'weight' for each building, "
                "then upload in Step 2 Grid Validation."
            ),
        )


def render_results_section(results: Optional[Dict[str, Any]], solve_time: Optional[float]) -> None:
    if results is None:
        st.info("No results yet. Configure inputs and click **Run LV design**.")
        return

    st.divider()
    st.header("Results")

    if solve_time is not None:
        st.caption(f"Model run time: {solve_time:.2f} s")

    _metric_row(results["metrics"])

    st.subheader("Distribution map")
    st.caption(
        "Green = grid-served buildings; Red = standalone candidates; "
        "Black = serving poles; Gray = support poles; Blue = LV network (MST)."
    )

    m = _make_map_lv(
        center=results["center"],
        gdf_served=results.get("gdf_served_4326"),
        gdf_unserved=results.get("gdf_unserved_4326"),
        gdf_poles=results.get("gdf_poles_4326"),
        mst_edges_latlon=results.get("mst_edges_latlon", []),
        gdf_roads=results.get("gdf_roads_4326"),
    )
    st_folium(m, height=600, width=900)

    _render_downloads(results.get("downloads", {}))
